---
abstract: 'Unicode IDNA Compatibility Processing (UTS #46)'
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-IDN-UTS46
no_index:
  directory:
    - eg
    - data
provides:
  Net::IDN::UTS46:
    file: lib/Net/IDN/UTS46.pm
    version: 0.999_20120101
  Net::IDN::UTS46::Mapping:
    file: lib/Net/IDN/UTS46/Mapping.pm
    version: 6.000000001
requires:
  Net::IDN::Punycode: 1.009
  Unicode::Normalize: 1
  perl: 5.008003
resources:
  license: http://dev.perl.org/licenses/
version: 0.999_20120101
